const words: Record<number, string[]> = {
  5: [
    "which",
    "there",
    "their",
    "about",
    "would",
    "these",
    "other",
    "words",
    "could",
    "write",
    "first",
    "water",
    "after",
    "where",
    "right",
    "think",
    "three",
    "years",
    "place",
  ],

  6: [
    "choice",
    "voices",
    "fruits",
    "mirror",
    "matter",
    "object",
    "circle",
    "thrive",
    "squash",
    "glimps",
    "strong",
    "whales",
    "garden",
    "candid",
    "elders",
    "people",
    "donate",
    "vision",
    "wanted",
    "friend",
  ],

  7: [
    "awesome",
    "balance",
    "concert",
    "freedom",
    "improve",
    "journey",
    "library",
    "maximize",
    "neutral",
    "outside",
    "package",
    "quality",
    "routine",
    "service",
    "typical",
    "upgrade",
    "version",
    "weather",
    "yankees",
    "zealous",
  ],

  8: [
    "abundant",
    "colorful",
    "creative",
    "decision",
    "friendly",
    "hardware",
    "influence",
    "language",
    "mountain",
    "numerous",
    "overcome",
    "pleasant",
    "rainbow",
    "solution",
    "triangle",
    "umbrella",
    "validate",
    "whisper",
    "zeppelin",
    "strength",
  ],
};

export const randomWord = (wordLength: number): string => {
  const wordsArray = words[wordLength];
  const randomIndex = Math.floor(Math.random() * wordsArray.length);
  return wordsArray[randomIndex];
};

export default words;
